urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^gpgvote/', include('gpgvote.foo.urls')),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', 
    {'document_root': '/path/to/gpgvote/templates/media'}),
    url(r'^captcha/', include('captcha.urls')),
    (r'^$', 'gpgvote.views.main'),
    (r'^userinfo/(?P<user_id>\d+)/$', 'gpgvote.views.userinfo'),
    (r'^register/$', 'gpgvote.gpgauth.views.register'),
    (r'^renew/(?P<username>.*)$', 'gpgvote.gpgauth.views.renew'),
    (r'^login/$', 'gpgvote.gpgauth.views.login_view'),
    (r'^logout/$', 'gpgvote.gpgauth.views.logout_view'),
    (r'^createpoll/$', 'gpgvote.polls.views.createpoll'),
    (r'^editpoll/(?P<poll_id>\d+)/$', 'gpgvote.polls.views.editpoll'),
    (r'^deletepoll/(?P<poll_id>\d+)/$', 'gpgvote.polls.views.deletepoll'),
    (r'^mypolls/$', 'gpgvote.polls.views.mypolls'),
    (r'^voters_list/(?P<poll_id>\d+)/$', 'gpgvote.polls.views.voters_list'),
    (r'^vote/(?P<poll_id>\d+)/$', 'gpgvote.polls.views.vote'),
    (r'^results/(?P<poll_id>\d+)/$', 'gpgvote.polls.views.results'),
    (r'^results/(?P<poll_id>\d+)/votes_list/$', 'gpgvote.polls.views.votes_list')
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

polls/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Poll(models.Model):
  creator = models.ForeignKey(User)
  question = models.TextField()
  min_choices = models.PositiveIntegerField()
  max_choices = models.PositiveIntegerField()
  allowed_voters = models.TextField('voters allowed to vote')
  who_voted = models.TextField('voters who have already voted')
  starts = models.DateTimeField()
  ends = models.DateTimeField()
    
  def __unicode__(self):
    return self.question
  
  def has_voted(self, voter):
    if voter in self.who_voted.split(';'):
      return True
    else:
      return False
 
  def add_voter(self, voter, To):
    if To == 'allowed_voters': 
      self.allowed_voters = self.allowed_voters + voter + ';' 
    elif To == 'who_voted':
      if voter in self.allowed_voters.split(';'):
        self.who_voted = self.who_voted + voter + ';'
      
  def remove_voter(self, voter, From):
    if From == 'allowed_voters': 
      self.allowed_voters = self.allowed_voters.replace(voter+';', '')
    elif From == 'who_voted':
      self.who_voted = self.who_voted.replace(voter+';', '')
      
  def is_allowed_voter(self, voter):
    if voter in self.allowed_voters.split(';'):
      return True
    else:
      return False
      
class Choice(models.Model):
  poll = models.ForeignKey(Poll)
  choice = models.CharField(max_length=255)
  
  def __unicode__(self):
    return self.choice
    
class Vote(models.Model):
  choice = models.ForeignKey(Choice)
  tag = models.CharField(max_length=35)
  
  def __unicode__(self):
    return '\'' + self.tag + '\' vote tag includes choice: ' + '\'' + str(self.choice) + '\''

polls/forms.py
from django import forms
from django.forms import TextInput, Textarea
from django.forms.extras.widgets import SelectDateWidget

class PollForm(forms.Form):
  question = forms.CharField(widget=Textarea(attrs={'rows':'3'}))
  min_choices = forms.IntegerField(widget=TextInput(attrs={'size':'2'}))
  max_choices = forms.IntegerField(widget=TextInput(attrs={'size':'2'}))
  starts_date = forms.DateField(widget=SelectDateWidget())
  starts_time = forms.TimeField(widget=TextInput(attrs={'size':'2'}))
  ends_date = forms.DateField(widget=SelectDateWidget())
  ends_time = forms.TimeField(widget=TextInput(attrs={'size':'2'}))
  allowed_voters = forms.MultipleChoiceField([])
  
  def __init__(self,allowed_voters,*args,**kwrds):
    super(PollForm,self).__init__(*args,**kwrds)
    self.fields['allowed_voters'].choices = allowed_voters
  

polls/views.py
from django.shortcuts import render_to_response
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.template import RequestContext
from django.conf import settings
from django.forms import Form
from gpgvote.polls.forms import PollForm
from django.contrib.auth.models import User
from gpgvote.gpgauth.models import PGPkey
from gpgvote.polls.models import Poll
from gpgvote.polls.models import Choice
from gpgvote.polls.models import Vote
from gnupg import GPG
import datetime
import random
import string
import operator


# Utility functions
def list_has_duplicates(mylist):
  if len(mylist) > len(list(set(mylist))):
    return True
  else:
    return False
  
def dates_check(starts_date, starts_time, ends_date, ends_time):
  error = ''
  starts_datetime = datetime.datetime(
                      year   = starts_date.year,
                      month  = starts_date.month,
                      day    = starts_date.day,
                      hour   = starts_time.hour,
                      minute = starts_time.minute,
                      second = starts_time.second  )
                      
  ends_datetime = datetime.datetime(
                    year   = ends_date.year,
                    month  = ends_date.month,
                    day    = ends_date.day,
                    hour   = ends_time.hour,
                    minute = ends_time.minute,
                    second = ends_time.second  )
  
  if starts_datetime < datetime.datetime.now() + datetime.timedelta(minutes = settings.POLL_START_TIME_THRESHOLD):
    error = '<ul><li>Poll must start at least ' + str(settings.POLL_START_TIME_THRESHOLD) + ' minutes in the future</li></ul>'
  
  duration = ends_datetime - starts_datetime
  if duration < datetime.timedelta(minutes = settings.POLL_MIN_DURATION):
    if duration < datetime.timedelta(microseconds=0):
      error = '<ul><li>Poll must end at least ' + str(settings.POLL_MIN_DURATION) + ' minutes after the start</li></ul>'
    else:
      error = '<ul><li>Poll must last for at least ' + str(settings.POLL_MIN_DURATION) + ' minutes</li></ul>'
  
  return error, starts_datetime, ends_datetime

def num_of_choices_check(num_of_choices, min_choices, max_choices):
  error = ''
  if max_choices < min_choices:
    error = '<ul><li>Max. must be bigger than or equal to Min.</li></ul>'
	
  if (max_choices < 1) or (min_choices < 1):
    error = '<ul><li>Max. and Min. must be bigger than or equal to 1</li></ul>'
  
  if (not error) and (max_choices > num_of_choices):
    error = '<ul><li>Max. and Min. must be smaller than or equal to the number of choices</li></ul>'
  
  return error

# Views
def poll(request, action, poll_id):
  if not request.user.is_authenticated():
    return HttpResponseRedirect('/')
  else:
    logged_in = True

  choices_error = ''
  dates_error = ''
  num_of_choices_error = ''
  allowed_voters_error = ''
  success = ''
  poll_data = {}
  poll_choices = []
  
  if action == 'edit':
    try:
      poll = Poll.objects.get(pk = poll_id)
    except Poll.DoesNotExist:
      raise Http404
    # allow edit only for creator and only if the poll has not started yet
    if (request.user != poll.creator) or (poll.starts < datetime.datetime.now()):
      return HttpResponseRedirect('/')
    poll_data = {    'question': poll.question,
                  'min_choices': poll.min_choices,
                  'max_choices': poll.max_choices,
                  'starts_date': poll.starts.date(),
                  'starts_time': poll.starts.time(),
                    'ends_date': poll.ends.date(),
                    'ends_time': poll.ends.time()   }
    poll_choices = Choice.objects.filter(poll = poll).order_by('id')
                         
  # Clean PGPkey records to correct is_trusted field
  for key in PGPkey.objects.all():
    key.clean()
  
  # Get trusted users and create allowed voters choices
  trusted_users = User.objects.filter(pgpkey__is_trusted=True).order_by('pgpkey__name')
  allowed_voters = ()
  for user in trusted_users:
    allowed_voters = allowed_voters + ( (user.username, user.pgpkey.name + ' <' + user.username + '>' ), )
  
  if request.POST:
    # allow edit only if the poll has not started yet
    if (action == 'edit'):
      if (poll.starts < datetime.datetime.now()):
        return HttpResponseRedirect('/')
      
    form = PollForm(allowed_voters, request.POST, initial = poll_data)
    if form.is_valid():
      poll_choices = request.POST.getlist('choices')
      if len(poll_choices) < 2:
        choices_error = '<ul><li>You must add at least 2 choices</li></ul>'
      else:
	for choice in poll_choices:
	  if len(choice) > 255:
	    choices_error = '<ul><li>Each choice must be up to 255 characters in length</li></ul>'
      
      (dates_error, starts_datetime, ends_datetime) = dates_check(
                                                        form.cleaned_data['starts_date'],
                                                        form.cleaned_data['starts_time'], 
                                                        form.cleaned_data['ends_date'],
                                                        form.cleaned_data['ends_time'] )
      num_of_choices_error = num_of_choices_check(len(poll_choices), 
                                                  form.cleaned_data['min_choices'], 
                                                  form.cleaned_data['max_choices'])                                                  
      if len(form.cleaned_data['allowed_voters']) < 2:
	allowed_voters_error = '<ul><li>You must select at least 2 voters</li></ul>'
      
      if not (choices_error or dates_error or num_of_choices_error or allowed_voters_error):
	if action == 'create':
	  poll = Poll(
	           creator = request.user,  
	           question = form.cleaned_data['question'],
	           min_choices = form.cleaned_data['min_choices'],
	           max_choices = form.cleaned_data['max_choices'],
	           allowed_voters = '',
	           who_voted = '',
	           starts = starts_datetime,
	           ends = ends_datetime )
	else:
	  poll.question = form.cleaned_data['question']
	  poll.min_choices = form.cleaned_data['min_choices']
	  poll.max_choices = form.cleaned_data['max_choices']
	  poll.allowed_voters = ''
          poll.starts = starts_datetime
	  poll.ends = ends_datetime
        
	for voter in form.cleaned_data['allowed_voters']:
	  poll.add_voter(voter, To = 'allowed_voters')
        poll.save()
        
        # Delete old choices before adding their new versions
        if action == 'edit':
          Choice.objects.filter(poll = poll).delete()
        for choice in poll_choices:
	  choice = Choice(poll = poll, choice = choice)
	  choice.save()

        if action == 'create':
	  success = 'You have successfully created a new poll'
	else:
	  success = 'You have successfully edited the poll'
  else:
    form = PollForm(allowed_voters, initial = poll_data)
  
  if action == 'edit':
    poll_id = poll.id
  else:
    poll_id = ''
    
  return render_to_response('poll.html', 
         {                 'form': form,
                         'action': action,
                        'poll_id': poll_id,
                        'choices': poll_choices,
                  'choices_error': choices_error,
                    'dates_error': dates_error,
           'num_of_choices_error': num_of_choices_error,
           'allowed_voters_error': allowed_voters_error,
                        'success': success,
                           'user': request.user.username,
                      'logged_in': logged_in }, context_instance = RequestContext(request))
                      
def createpoll(request):
  return poll(request, 'create', None)
  
def editpoll(request, poll_id):
  return poll(request, 'edit', poll_id)
  
def deletepoll(request, poll_id):
  if not request.user.is_authenticated():
    return HttpResponseRedirect('/')
  else:
    logged_in = True
    
  try:
      poll = Poll.objects.get(pk = poll_id)
  except Poll.DoesNotExist:
      raise Http404
  
  # Delete poll only if it has not started yet and the user is the creator of the poll
  if (poll.creator == request.user) and (poll.starts > datetime.datetime.now()):
    poll.delete()
  
  return HttpResponseRedirect('/mypolls')
  
def mypolls(request):
  if not request.user.is_authenticated():
    return HttpResponseRedirect('/')
  else:
    logged_in = True
  
  # Polls that are created by the user and polls for which the user is allowed to vote
  mypolls_query = Poll.objects.filter(Q(creator = request.user) 
                                | Q(allowed_voters__contains = request.user.username + ';')).order_by('ends')
  
  pending_polls = []
  ended_polls = []
  for poll in mypolls_query:
    poll_has_ended = False
    if poll.ends < datetime.datetime.now():
       poll_has_ended = True
    if poll.starts < datetime.datetime.now():
      if poll.has_voted(request.user.username):
	if poll.ends < datetime.datetime.now():
	  poll_has_ended = True
	  allowed_actions = 'results'
	else:
	  allowed_actions = 'wait' # You have already voted but the poll has not ended yes, so, wait
      else:
	if poll.is_allowed_voter(request.user.username):
	  allowed_actions = 'vote'
	else:
	  allowed_actions = 'wait_creator' # You cannot vote, but you are the creator of the poll 
	                                   # and allowed to see the results 
    else:
      if poll.creator == request.user:
	allowed_actions = 'edit'
      else:
	allowed_actions = ''
    if poll_has_ended:
      ended_polls = ended_polls + [{ 'poll': poll, 'allowed_actions': allowed_actions }]
    else:
      if allowed_actions:
	pending_polls = pending_polls + [{ 'poll': poll, 'allowed_actions': allowed_actions }]
  
  ''' mypolls_query ordered the polls by ending datetime. So, we reverse ended_polls to have
      the 'fresher' results in the top '''
  ended_polls.reverse()
  
  return render_to_response('mypolls.html',

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <link rel="stylesheet" href="/site_media/css/style.css" />
    <script src="/site_media/js/gpgvote.js" language="javascript" type="text/javascript"></script>
    <title>{% block title %}GPGVote{% endblock %}</title>
  </head>

  <body>

    <div id="header">
      <img src="/site_media/images/gpgvote_logo.png" />
    </div>

    <div id="menubar">
      <div id="site_actions">
        <ul id="menulist">
          <li><a href="/">Home</a></li>
          {% if not logged_in %}
            <li><a href="/register/">Register</a></li>
          {% endif %}
        </ul>
      </div>
 
      <div id="login_actions">
        <ul id="menulist">
           {% if not logged_in %}
             <li><a href="/login/">Login</a></li>
           {% endif %}
           {% if logged_in %}
             <li><b>logged in as: </b>{{ user }}</li>
             <li><a href="/logout/">Logout</a></li>
           {% endif %}
        </ul>
      </div>
    </div>

    <div id="content">
      {% block content %}{% endblock %}
    </div>

  </body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
      <h2>Login:</h2>
      <div style="text-align:center">
      {% if error %}
      <p style="color:red"><b>Error: </b>{{ error }}</p>
      {% endif %}
      {% if form %}
      <form action="/login/" method="post">
        {% csrf_token %}
        <p><b>Username:</b> {{ form.username }}</p>
        {% if goto_stage = "afterpass" %}
        <p>Decrypt the following PGP-encrypted password with your Private Key and use it in the password field below:</p> 
        <div id="vote_receipt"><pre>{{ password }}</pre></div>
        <p><b>Password:</b> {{ form.password }}</p>
        {% endif %}
        <input type="hidden" name="stage" value="{{ goto_stage }}" />
        <input style="font-weight:bold;font-size:large" type="submit" value="Login" />
      </form>
      {% endif %}
      </div>
{% endblock %} 

templates/main.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
      <h2>Welcome to GPGVote!</h2>
      <p>
        <b>GPGVote</b> is a <b><i>Web-based electronic voting system</i></b> that implements its security requirements with the use 
        of <b><i>PGP keys</i></b>.
      </p>
      <p>
        GPGVote is considered an academic project, originally designed and implemented by 
        <a href="mailto:ernest0x@dtps.unipi.gr">Petros Moisiadis</a> as his graduate thesis in Information Technology.
      <p>
      {% if logged_in %}
      <div id="main_functions">
        <table cellspacing="40" cellpadding="25" align="center">
          <tr>
            <td><a href="./mypolls/"><img src="/site_media/images/mypolls.png" /></a><br /><b>My Polls</b></td>
            <td><a href="./createpoll/"><img src="/site_media/images/create_poll.png" /></a><br /><b>Create Poll</b></td>
          </tr>
        </table>
      </div>
      {% endif %}
{% endblock %} 

templates/mypolls.html
{% extends "base.html" %}

{% block title %}My Polls{% endblock %}

{% block content %}
      {% if pending_polls %}<h2>Pending Polls:</h2>{% endif %}
        {% for p in pending_polls %}
          {% if p.allowed_actions %}
            <table id="poll_table" align="center">
              <tr>
                <th>Poll Question</th>
                <td><b>{{ p.poll.question }}</b></td>
              </tr>
              <tr>
                <th>Created by:</th>
                <td>
                  <a href="/userinfo/{{ p.poll.creator.id }}">
                    {{ p.poll.creator.pgpkey.name }} &lt;{{ p.poll.creator.username }}&gt;
                  </a>
                </td>
              </tr>
              <tr>
                <th>Allowed Voters:</th>
                <td>
                  <a href="/voters_list/{{ p.poll.id }}">Show list of allowed voters</a>
                </td>
              </tr>
              <tr>
                <th>{% if p.allowed_actions == 'edit' %}Starts:{% else %}Started:{% endif %}</th>
                <td>{{ p.poll.starts }}</td>
              </tr>
              <tr>
                <th>Ends:</th>
                <td>{{ p.poll.ends }}</td>
              </tr>
              <tr>
                <th>Actions:</th>
                <td>
                  <ul id="menulist">
                    {% if p.allowed_actions == 'edit' %}
                      <li>
                        <a href="/editpoll/{{ p.poll.id }}"><img class="textmiddle" src="/site_media/images/poll_edit.png" /> Edit</a>
                      </li>
                      <li>
                        <a href="#" onclick="delconfirm('{{ p.poll.id }}')">
                          <img class="textmiddle" src="/site_media/images/poll_delete.png" /> Delete
                        </a>
                      </li>
                    {% endif %}
                    {% if p.allowed_actions == 'vote' %}
                      <li>
                        <a href="/vote/{{ p.poll.id }}"><img class="textmiddle" src="/site_media/images/vote.png" /> Vote</a>
                      </li>
                    {% endif %}
                    {% if p.allowed_actions == 'results' %}
                      <li>
                        <a href="/results/{{ p.poll.id }}"><img class="textmiddle" src="/site_media/images/results.png" /> Results</a>
                      </li>
                    {% endif %}
                    {% if p.allowed_actions == 'wait' %}<i>You have already voted. Please, wait for the results.</i>{% endif %}
                    {% if p.allowed_actions == 'wait_creator' %}<i>Please, wait for the results.</i>{% endif %}
                  </ul>
                </td>
              </tr>
            </table>
            <br />
          {% endif %}
        {% endfor %}
        
      {% if ended_polls %}
        <h2>Ended Polls:</h2>
      {% endif %}
        {% for p in ended_polls %}
            <table id="poll_table" align="center">
              <tr>
                <th>Poll Question</th>
                <td><b>{{ p.poll.question }}</b></td>
              </tr>
              <tr>
                <th>Created by:</th>
                <td>
                  <a href="/userinfo/{{ p.poll.creator.id }}">
                    {{ p.poll.creator.pgpkey.name }} &lt;{{ p.poll.creator.username }}&gt;
                  </a>
                </td>
              </tr>
              <tr>
                <th>Allowed Voters:</th>
                <td>
                  <a href="/voters_list/{{ p.poll.id }}">Show list of allowed voters</a>
                </td>
              </tr>
              <tr>
                <th>Started:</th>
                <td>{{ p.poll.starts }}</td>
              </tr>
              <tr>
                <th>Ended:</th>
                <td>{{ p.poll.ends }}</td>
              </tr>
              <tr>
                <th>Actions:</th>
                <td>
                  <ul id="menulist">
                    <li>
                      <a href="/results/{{ p.poll.id }}"><img class="textmiddle" src="/site_media/images/results.png" /> Results</a>
                    </li>
                  </ul>
                </td>
              </tr>
            </table>
            <br />
        {% endfor %}
      
{% endblock %} 

templates/poll.html
{% extends "base.html" %}

{% block title %}Create Poll{% endblock %}

{% block content %}
      <h2>{{ action|capfirst }} your Poll:</h2>
      {% if not success %}
      {% if action == "create" %}
      <form action="/createpoll/" method="post">
      {% else %}
      <form action="/editpoll/{{ poll_id }}/" method="post">
      {% endif %}
        {% csrf_token %}
        <br />
        <table cellpadding="10" align="center">
           <tr>
              <td valign="top" style="border-right: 1px dashed green">

                <table id="poll_edit">
                  <tr><th>Question:</th></tr>
                  <tr><td>{{ form.question }}</td></tr>
                  <tr><td id="error_td">{{ form.question.errors }}</td></tr>
                  <tr><td colspan="2">&nbsp;</td></tr>
                  <tr><th>Choice:</th></tr>
                  <tr><td><textarea id="id_choice" rows="2" name="choice"></textarea></td></tr>
                  <tr>
                    <td align="center">
                      <input type="button" value="Add Choice" name="add_choice" onclick="addChoice('id_choice', 'id_choices')" />
                    </td>
                  </tr>
                  <tr><td colspan="2">&nbsp;</td></tr>
                  <tr><th>Added Choices:</th></tr>
                  <tr>
                    <td>
                      <select multiple="multiple" id="id_choices" name="choices">
                        {% for choice in choices %}
                          <option value="{{ choice }}">{{ choice}}</option>
                        {% endfor %}
                      </select>
                    </td>
                  </tr>
                  <tr><td id="error_td">{{ choices_error|safe }}</td></tr></tr>
                  <tr>
                    <td align="center">
                      <input type="button" value="Remove Choice(s)" name="remove_choice" onclick="removeChoices('id_choices')"/>
                    </td>
                  </tr>
                </table>

              </td>
              <td valign="top">

                <table id="poll_edit">
                  <tr><th align="left">Min. number of choices per vote:</th></tr><tr><td>{{ form.min_choices }}</td></tr>
                  <tr><th align="left">Max. number of choices per vote:</th></tr><tr><td>{{ form.max_choices }}</td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.max_choices.errors }} {{ num_of_choices_error|safe }}</td></tr>
                  <tr><td colspan="2">&nbsp;</td></tr>
                  <tr><th colspan="2">Starts:</th></tr>
                  <tr><td colspan="2">Date: {{ form.starts_date }}</td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.starts_date.errors }}  {{ dates_error|safe }}</td></tr>
                  <tr><td colspan="2">Time: {{ form.starts_time }} <small><i> (in "hh:mm" format)</i></small></td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.starts_time.errors }}</td></tr>
                  <tr><td colspan="2">&nbsp;</td></tr>
                  <tr><th colspan="2">Ends:</th></tr>
                  <tr><td colspan="2">Date: {{ form.ends_date }}</td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.ends_date.errors }}  {{ dates_error|safe }}</td></tr>
                  <tr><td colspan="2">Time: {{ form.ends_time }} <small><i> (in "hh:mm" format)</i></small></td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.ends_time.errors }}</td></tr>
                  <tr><td colspan="2">&nbsp;</td></tr>
                  <tr><th colspan="2">Select Voters:</th></tr>
                  <tr><td colspan="2">{{ form.allowed_voters }}</td></tr>
                  <tr><td colspan="2" id="error_td">{{ form.allowed_voters.errors }} {{ allowed_voters_error|safe }}</td></tr>
                  <tr>
                    <td colspan="2" align="center">
                      <input type="button" value="None" name="select_none" onclick="selectChoices('none', 'id_allowed_voters')" />
                      <input type="button" value="All" name="select_all" onclick="selectChoices('all', 'id_allowed_voters')" />
                    </td>
                  </tr>
                </table>

              </td>
           </tr>
           <tr><td colspan="2"><hr /></td></tr>
        </table>
        <div align="center">
          <input style="font-size: large; font-weight: bold" type="submit" value="{{ action|capfirst }} Poll" onclick="selectChoices('all', 'id_choices')" />
        </div>
      </form>
      {% else %}
      <p>{{ success }}</p>
      {% endif %}
{% endblock %} 

templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
      <div style="text-align:center">
      <h2>Register:</h2>
      <p>Please, upload your public key.</p>
      {% if not success %}
      {% if error %}<p style="color:red"><b>Error:</b> {{ error }}</p>{% endif %}
      <form enctype="multipart/form-data" action="/register/" method="post">
        {% csrf_token %}
        <b>{{ form.as_p }}</b>
        <input style="font-weight:bold;font-size:large" type="submit" value="Register" />
      </form>
      {% endif %}
      {% if success %}
      <p><b>Success:</b> {{ success }}</p>
      {% endif %}
      </div>
{% endblock %} 

templates/renew.html
{% extends "base.html" %}

{% block title %}Renew Key{% endblock %}

{% block content %}
      <h2>Renew your key:</h2>
      {% if not success %}
        {% if error %}<p style="text-align:center;color:red"><b>Error:</b> {{ error }}</p>
        {% else %}
          <p style="text-align:center">Your key has expired. You can renew your key here.
          <br/>The required password has been sent to your email address.</p>
          <p style="text-align:center">Please, upload your public key.<br /><br />
          <form style="text-align:center" enctype="multipart/form-data" action="/renew/{{ username }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Renew" />
          </form>
          </p>
        {% endif %}
      {% endif %}
      {% if success %}
      <p style="text-align:center"><b>Success:</b> {{ success }}</p>
      {% endif %}
{% endblock %} 

templates/userinfo.html
{% extends "base.html" %}

{% block title %}My Polls{% endblock %}

{% block content %}
      <h2>User Info:</h2>
      <table id="userinfo_table" align="center">
        <tr>
          <th>Name:</th>
          <td><b>{{ requested_user.pgpkey.name }}</b></td>
        </tr>
        <tr>
          <th>E-mail:</th>
          <td><a href="mailto:{{ requested_user.email }}">{{ requested_user.email }}</a></td>
        </tr>
        <tr>
          <th>Public PGP key fingerprint:</th>
          <td>{{ requested_user.pgpkey }}</td>
        </tr>
        <tr>
          <th>Trusted by the Authority:</th>
          <td>
            {% if requested_user.pgpkey.is_trusted %}
              <span style="color:green">Yes</span>
            {% else %}
              <span style="color:red">No</span>
            {% endif %}
          </td>
        </tr>
      </table>

{% endblock %} 